const dummyEmployees = [
  {
    id: '1',
    firstName: 'Alice',
    lastName: 'Johnson',
    dateOfEmployment: '2021-05-15',
    dateOfBirth: '1990-01-20',
    phone: '555-1234',
    email: 'alice.johnson@example.com',
    department: 'tech',
    position: 'junior',
  },
  {
    id: '2',
    firstName: 'Bob',
    lastName: 'Williams',
    dateOfEmployment: '2020-08-01',
    dateOfBirth: '1985-11-05',
    phone: '555-5678',
    email: 'bob.williams@example.com',
    department: 'analytics',
    position: 'medior',
  },
  {
    id: '3',
    firstName: 'Charlie',
    lastName: 'Davis',
    dateOfEmployment: '2019-06-10',
    dateOfBirth: '1993-03-15',
    phone: '555-9101',
    email: 'charlie.davis@example.com',
    department: 'tech',
    position: 'senior',
  },
  {
    id: '4',
    firstName: 'Diana',
    lastName: 'Clark',
    dateOfEmployment: '2022-01-12',
    dateOfBirth: '1997-07-22',
    phone: '555-2345',
    email: 'diana.clark@example.com',
    department: 'analytics',
    position: 'junior',
  },
  {
    id: '5',
    firstName: 'Evan',
    lastName: 'Martinez',
    dateOfEmployment: '2018-11-05',
    dateOfBirth: '1988-12-09',
    phone: '555-6789',
    email: 'evan.martinez@example.com',
    department: 'tech',
    position: 'medior',
  },
  {
    id: '6',
    firstName: 'Fiona',
    lastName: 'Taylor',
    dateOfEmployment: '2020-03-18',
    dateOfBirth: '1995-05-27',
    phone: '555-3456',
    email: 'fiona.taylor@example.com',
    department: 'analytics',
    position: 'senior',
  },
  {
    id: '7',
    firstName: 'George',
    lastName: 'Harris',
    dateOfEmployment: '2019-09-14',
    dateOfBirth: '1992-02-11',
    phone: '555-4567',
    email: 'george.harris@example.com',
    department: 'tech',
    position: 'junior',
  },
  {
    id: '8',
    firstName: 'Hannah',
    lastName: 'Lopez',
    dateOfEmployment: '2021-07-30',
    dateOfBirth: '1994-06-19',
    phone: '555-7890',
    email: 'hannah.lopez@example.com',
    department: 'analytics',
    position: 'medior',
  },
  {
    id: '9',
    firstName: 'Ian',
    lastName: 'Walker',
    dateOfEmployment: '2018-04-22',
    dateOfBirth: '1991-10-03',
    phone: '555-8901',
    email: 'ian.walker@example.com',
    department: 'tech',
    position: 'senior',
  },
  {
    id: '10',
    firstName: 'Julia',
    lastName: 'Garcia',
    dateOfEmployment: '2022-08-19',
    dateOfBirth: '1998-08-25',
    phone: '555-0123',
    email: 'julia.garcia@example.com',
    department: 'analytics',
    position: 'junior',
  },
  {
    id: '11',
    firstName: 'Kevin',
    lastName: 'White',
    dateOfEmployment: '2020-10-11',
    dateOfBirth: '1993-04-07',
    phone: '555-3457',
    email: 'kevin.white@example.com',
    department: 'tech',
    position: 'medior',
  },
  {
    id: '12',
    firstName: 'Laura',
    lastName: 'Young',
    dateOfEmployment: '2019-12-03',
    dateOfBirth: '1989-09-13',
    phone: '555-6780',
    email: 'laura.young@example.com',
    department: 'analytics',
    position: 'senior',
  },
];

export default dummyEmployees;
